using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using MotionPlanningSim.Environment;
using Unity.Pipeline.Commands;
using UnityEditor;
using UnityEngine;

namespace MotionPlanningSim.Editor
{
    // Exports the Nav2 map's navigation colliders as 3D boxes for the MoveIt planning scene
    // (ROS map frame). Same source colliders and height band as Nav2MapExporter. Box colliders
    // rotated only about the vertical (the gate approach walls) keep their true size and yaw;
    // other colliders use their world bounds, which over-approximate them.
    public static class PlanningBoxExporter
    {
        private const string FileName = "construction_site.boxes.yaml";

        [MenuItem("Tools/Motion Planning/Export Construction Site Planning Boxes")]
        [CliCommand(
            "export_planning_boxes",
            "Export ConstructionSiteV1 navigation colliders as 3D boxes for the MoveIt planning scene",
            MainThreadRequired = true)]
        public static string ExportPlanningBoxes()
        {
            var (yaml, count) = BuildYaml();
            var path = OutputPath();
            File.WriteAllText(path, yaml, new UTF8Encoding(false));
            return $"Exported {count} planning boxes to {path}.";
        }

        [MenuItem("Tools/Motion Planning/Validate Construction Site Planning Boxes")]
        [CliCommand(
            "validate_planning_boxes",
            "Validate the committed MoveIt planning boxes against current ConstructionSiteV1 colliders",
            MainThreadRequired = true)]
        public static string ValidatePlanningBoxes()
        {
            var (yaml, count) = BuildYaml();
            var path = OutputPath();
            if (!File.Exists(path))
                throw new InvalidOperationException("Planning boxes are missing; run export_planning_boxes.");
            if (!string.Equals(File.ReadAllText(path), yaml, StringComparison.Ordinal))
                throw new InvalidOperationException("Planning boxes are stale relative to scene navigation colliders.");
            return $"Validated {count} planning boxes in {path}.";
        }

        private static string OutputPath() => Path.Combine(Nav2MapExporter.GetMapOutputDirectory(), FileName);

        private static (string yaml, int count) BuildYaml()
        {
            var scene = Nav2MapExporter.OpenConstructionScene();
            var colliders = Nav2MapExporter.NavigationColliders(Nav2MapExporter.NavigationObstaclesRoot(scene))
                .Where(Nav2MapExporter.InMapBand)
                .ToArray();
            var builder = new StringBuilder();
            builder.Append("# Generated by PlanningBoxExporter from NavigationObstacles; do not edit.\n");
            builder.Append("frame_id: map\n");
            builder.Append($"source_scene: {Nav2MapExporter.SourceScenePath}\n");
            builder.Append("boxes:\n");
            foreach (var collider in colliders)
            {
                var box = Oriented(collider) ?? PlanningBoxGeometry.UnityBoundsToRos(collider.bounds);
                var name = Nav2MapExporter.GetHierarchyPath(collider.transform)
                    .Replace("\\", "\\\\").Replace("\"", "\\\"");
                builder.Append($"  - {{name: \"{name}\", center: [{F(box.Center.x)}, {F(box.Center.y)}, {F(box.Center.z)}], " +
                               $"size: [{F(box.Size.x)}, {F(box.Size.y)}, {F(box.Size.z)}], yaw: {F(box.Yaw)}}}\n");
            }
            return (builder.ToString(), colliders.Length);
        }

        private static RosBox? Oriented(Collider collider)
        {
            if (!(collider is BoxCollider box))
                return null;
            var t = box.transform;
            var scale = t.lossyScale;
            var size = Vector3.Scale(box.size, new Vector3(Mathf.Abs(scale.x), Mathf.Abs(scale.y), Mathf.Abs(scale.z)));
            return PlanningBoxGeometry.TryUnityOrientedBoxToRos(t.TransformPoint(box.center), size, t.rotation, out var oriented)
                ? oriented
                : (RosBox?)null;
        }

        private static string F(float value) => value.ToString("F4", CultureInfo.InvariantCulture);
    }
}
