services:
  ma-robot-sim:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-jazzy}
        # Low-memory build mode:
        # COLCON_BUILD_MODE: ${COLCON_BUILD_MODE:-queued}
        # COLCON_PARALLEL_WORKERS: ${COLCON_PARALLEL_WORKERS:-1}
        # CMAKE_BUILD_PARALLEL_LEVEL: ${CMAKE_BUILD_PARALLEL_LEVEL:-1}
        # MAKEFLAGS: ${MAKEFLAGS:--j1}
        # ROS2_WS_CMAKE_BUILD_TYPE: ${ROS2_WS_CMAKE_BUILD_TYPE:-Release}
    image: ma-robot-sim:${ROS_DISTRO:-jazzy}
    command: sleep infinity
    init: true
    tty: true
    stdin_open: true
    ipc: host
    shm_size: "4gb"
    privileged: true
    ports:
      - "6080:6080"   # noVNC browser desktop
      - "8080:8080"   # optional project/web visualizer port
      - "7681:7681"   # optional ttyd/web terminal if you add it later
      - "10000:10000" # Unity ROS-TCP-Connector endpoint
    volumes:
      - ..:/mt-mohamad-nassif
    environment:
      ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-0}"
      ROS_LOCALHOST_ONLY: "${ROS_LOCALHOST_ONLY:-0}"
      RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
      DISPLAY: "${DISPLAY:-:0}"
      QT_X11_NO_MITSHM: "1"
      NOVNC_DISPLAY: "${NOVNC_DISPLAY:-:99}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
